name: 'Movie Picture Pipeline'
on:
  pull_request:
    branches:
      - main
    path:
      - 'frontend/**'
  workflow_dispatch:

env:
  WORKING_DIR: ../Thim-Movie-Picture/frontend

jobs:
  setup:
    name: Set up project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies 
        run: npm ci 
       
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
        
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run:  npm run lint
        
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pipenv install

      - name: Run Tests
        run: pipenv run test
  
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [setup,lint,test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-build-action@v3

      - name: Build Docker image
        run: docker build -t frontend-app ./frontend


