name: 'Movie Picture Pipeline'
on:
  pull_request:
    branches:
      - main
    path:
      - 'frontend/**'
  workflow_dispatch:

env:
  WORKING_DIR: ../Thim-Movie-Picture/frontend

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install 
        
      
      - name: Run ESLint
        run: pipenv run lint
        

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pipenv install

      - name: Run Tests
        run: pipenv run test
  
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint,test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-build-action@v3

      - name: Build Docker image
        run: docker build -t frontend-app ./frontend


