name: 'Movie Picture Pipeline'
on:
  pull_request:
    branches:
      - main
    path:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
