name: 'Movie Picture Pipeline'
on:
  pull_request:
    branches:
      - main
    path:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install 
        working-directory: frontend
      
      - name: Run ESLint
        run: npm run lint
        working-directory: frontend

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
  
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint,test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-build-action@v3

      - name: Build Docker image
        run: docker build -t frontend-app ./frontend


