name: 'Movie Picture Pipeline'
on:
  pull_request:
    branches:
      - main
    path:
      - 'frontend/**'
  workflow_dispatch:

env:
  WORKING_DIR: ../Thim-Movie-Picture/frontend

jobs:
       
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
        
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Run ESLint
        run:  npm run lint -- --fix 
        working-directory: ${{ env.WORKING_DIR }}
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Run Tests
        run: npm test
        working-directory: ${{ env.WORKING_DIR }}
  
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint,test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-build-action@v3

      - name: Build Docker image
        run: docker build -t frontend-app ./frontend


